sudo: required

language: generic

services:
    - docker

before_install:
    - echo "start createing"
    - docker build -t dudckd/travis -f dockerfile.dev .

script:
    - docker run -e CI=true dudckd/travis npm run test -- --coverage

deploy:
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "docker-react"
    env: "DockerReact-env"
    bucket_name: "elasticbeanstalk-us-east-2-840213432037"
    bucket_path: "docker-react"
    on:
        branch: master
        
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_ACCESS_KEY